# Generated by Django 4.2.23 on 2025-09-24 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del punto de atención', max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(help_text='Dirección física del punto de atención', max_length=255, verbose_name='Dirección')),
                ('horario_atencion', models.CharField(help_text='Horario de funcionamiento del punto', max_length=100, verbose_name='Horario de Atención')),
                ('es_activo', models.BooleanField(default=True, help_text='Indica si el punto está activo', verbose_name='Activo')),
                ('fecha_instalacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha en que se instaló el punto', verbose_name='Fecha de Instalación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tauser',
                'verbose_name_plural': 'Tausers',
                'ordering': ['nombre'],
                'permissions': [('deactivate_tauser', 'Can deactivate tauser')],
            },
        ),
    ]
