# Generated by Django 4.2.23 on 2025-10-03 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0004_moneda_monto_limite_transaccion'),
        ('tauser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad disponible en stock', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('cantidad_minima', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad mínima antes de alertar', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima')),
                ('es_activo', models.BooleanField(default=True, help_text='Indica si este stock está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('moneda', models.ForeignKey(help_text='Moneda del stock', on_delete=django.db.models.deletion.CASCADE, to='monedas.moneda', verbose_name='Moneda')),
                ('tauser', models.ForeignKey(help_text='Punto de atención al que pertenece este stock', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tauser.tauser', verbose_name='Tauser')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['tauser', 'moneda'],
                'permissions': [('manage_stock', 'Can manage stock')],
                'unique_together': {('tauser', 'moneda')},
            },
        ),
    ]
