# Generated by Django 4.2.23 on 2025-10-08 21:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transacciones', '0004_transaccion_tauser_alter_transaccion_cliente_and_more'),
        ('tauser', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], help_text='Si es entrada o salida de stock', max_length=10, verbose_name='Tipo de Movimiento')),
                ('origen_movimiento', models.CharField(choices=[('MANUAL', 'Manual'), ('TRANSACCION', 'Transacción')], help_text='Si fue manual o por transacción', max_length=15, verbose_name='Origen del Movimiento')),
                ('cantidad_movida', models.DecimalField(decimal_places=2, help_text='Cantidad que se movió en este registro', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Movida')),
                ('cantidad_anterior', models.DecimalField(decimal_places=2, help_text='Cantidad que había antes del movimiento', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Anterior')),
                ('cantidad_posterior', models.DecimalField(decimal_places=2, help_text='Cantidad que quedó después del movimiento', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Posterior')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del movimiento', verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó el movimiento', verbose_name='Fecha del Movimiento')),
                ('stock', models.ForeignKey(help_text='Stock al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tauser.stock', verbose_name='Stock')),
                ('transaccion', models.ForeignKey(blank=True, help_text='Transacción relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacciones.transaccion', verbose_name='Transacción')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Stock',
                'verbose_name_plural': 'Historial de Stocks',
                'ordering': ['-fecha_movimiento'],
                'permissions': [('view_historial_stock', 'Can view stock history')],
            },
        ),
    ]
