# Generated by Django 4.2.23 on 2025-10-14 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0005_denominacionmoneda'),
        ('transacciones', '0004_transaccion_tauser_alter_transaccion_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tauser', '0003_historialstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad de billetes/monedas de esta denominación', verbose_name='Cantidad')),
                ('es_activo', models.BooleanField(default=True, help_text='Indica si este stock de denominación está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('denominacion', models.ForeignKey(help_text='Denominación específica (billete/moneda)', on_delete=django.db.models.deletion.CASCADE, to='monedas.denominacionmoneda', verbose_name='Denominación')),
                ('stock', models.ForeignKey(help_text='Stock al que pertenece esta denominación', on_delete=django.db.models.deletion.CASCADE, related_name='stock_denominaciones', to='tauser.stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Stock por Denominación',
                'verbose_name_plural': 'Stocks por Denominación',
                'ordering': ['stock', 'denominacion__valor'],
                'permissions': [('manage_stock_denominacion', 'Can manage stock by denomination')],
                'unique_together': {('stock', 'denominacion')},
            },
        ),
        migrations.CreateModel(
            name='HistorialStockDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], help_text='Si es entrada o salida de stock', max_length=10, verbose_name='Tipo de Movimiento')),
                ('origen_movimiento', models.CharField(choices=[('MANUAL', 'Manual'), ('TRANSACCION', 'Transacción')], help_text='Si fue manual o por transacción', max_length=15, verbose_name='Origen del Movimiento')),
                ('cantidad_movida', models.PositiveIntegerField(help_text='Cantidad de billetes/monedas que se movió', verbose_name='Cantidad Movida')),
                ('cantidad_anterior', models.PositiveIntegerField(help_text='Cantidad que había antes del movimiento', verbose_name='Cantidad Anterior')),
                ('cantidad_posterior', models.PositiveIntegerField(help_text='Cantidad que quedó después del movimiento', verbose_name='Cantidad Posterior')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del movimiento', verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó el movimiento', verbose_name='Fecha del Movimiento')),
                ('stock_denominacion', models.ForeignKey(help_text='Stock de denominación al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tauser.stockdenominacion', verbose_name='Stock Denominación')),
                ('transaccion', models.ForeignKey(blank=True, help_text='Transacción relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacciones.transaccion', verbose_name='Transacción')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Stock por Denominación',
                'verbose_name_plural': 'Historial de Stocks por Denominación',
                'ordering': ['-fecha_movimiento'],
                'permissions': [('view_historial_stock_denominacion', 'Can view stock denomination history')],
            },
        ),
    ]
