# Generated by Django 4.2.23 on 2025-10-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0007_merge_20251024_0734'),
        ('tauser', '0004_stockdenominacion_historialstockdenominacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacionRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código de Verificación')),
                ('tipo', models.CharField(choices=[('retiro', 'Retiro de Efectivo')], default='retiro', max_length=20, verbose_name='Tipo de Verificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_verificacion_retiro', to='transacciones.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Código de Verificación de Retiro',
                'verbose_name_plural': 'Códigos de Verificación de Retiro',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo', 'tipo'], name='tauser_codi_codigo_29404e_idx'), models.Index(fields=['transaccion', 'tipo'], name='tauser_codi_transac_9f5ca7_idx'), models.Index(fields=['fecha_expiracion'], name='tauser_codi_fecha_e_9fd609_idx')],
            },
        ),
    ]
