# Generated by Django 4.2.23 on 2025-10-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0005_codigoverificacionretiro'),
    ]

    operations = [
    ]
