# Generated by Django 4.2.23 on 2025-10-15 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0004_moneda_monto_limite_transaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tasa_cambio', 'Cambio de Tasa'), ('sistema', 'Sistema'), ('alerta', 'Alerta')], default='sistema', help_text='Tipo de notificación', max_length=20)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje detallado de la notificación')),
                ('leida', models.BooleanField(default=False, help_text='Indica si la notificación fue leída')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Fecha y hora en que se leyó la notificación', null=True)),
                ('precio_base_anterior', models.PositiveIntegerField(blank=True, help_text='Precio base anterior (si aplica)', null=True)),
                ('precio_base_nuevo', models.PositiveIntegerField(blank=True, help_text='Precio base nuevo (si aplica)', null=True)),
                ('moneda', models.ForeignKey(blank=True, help_text='Moneda relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='monedas.moneda')),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones_notificacion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='notificacio_usuario_b76847_idx'), models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx')],
            },
        ),
    ]
