# Generated by Django 4.2.23 on 2025-10-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('tasa_cambio', 'Cambio de Tasa')], default='tasa_cambio', help_text='Tipo de notificación', max_length=20),
        ),
    ]
