# Generated by Django 4.2.23 on 2025-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='comision_compra_anterior',
            field=models.PositiveIntegerField(blank=True, help_text='Comisión de compra anterior (si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='comision_compra_nueva',
            field=models.PositiveIntegerField(blank=True, help_text='Comisión de compra nueva (si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='comision_venta_anterior',
            field=models.PositiveIntegerField(blank=True, help_text='Comisión de venta anterior (si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='comision_venta_nueva',
            field=models.PositiveIntegerField(blank=True, help_text='Comisión de venta nueva (si aplica)', null=True),
        ),
    ]
