# Generated by Django 4.2.23 on 2025-10-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_notificacion_comision_compra_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='metodo_pago',
            field=models.CharField(blank=True, help_text='Método de pago utilizado (si aplica)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='monto_pago',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del pago realizado (si aplica)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID de la transacción relacionada (si aplica)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('tasa_cambio', 'Cambio de Tasa'), ('pago_exitoso', 'Pago Exitoso')], default='tasa_cambio', help_text='Tipo de notificación', max_length=20),
        ),
    ]
