# Generated by Django 4.2.23 on 2025-08-29 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la moneda (ej: Dólar Estadounidense)', max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código ISO 4217 de la moneda (ej: USD, EUR, PYG)', max_length=3, unique=True)),
                ('simbolo', models.CharField(help_text='Símbolo de la moneda (ej: $, €, ₲)', max_length=5)),
                ('es_activa', models.BooleanField(default=True, help_text='Indica si la moneda está activa para operaciones')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'monedas_moneda',
                'ordering': ['nombre'],
            },
        ),
    ]
