# Generated by Django 4.2.23 on 2025-08-29 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='decimales',
            field=models.PositiveSmallIntegerField(default=2, help_text='Número de decimales que usa la moneda (ej: 2 para USD, 0 para JPY)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
