# Generated by Django 4.2.23 on 2025-08-29 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0002_moneda_decimales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='decimales',
            field=models.PositiveSmallIntegerField(default=2, help_text='Número de decimales que usa la moneda (ej: 2 para USD, 0 para JPY)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
