# Generated by Django 4.2.23 on 2025-09-23 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0003_alter_moneda_decimales'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='monto_limite_transaccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo permitido para una sola transacción en esta moneda. Vacío = sin límite.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
