# Generated by Django 4.2.23 on 2025-10-14 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0004_moneda_monto_limite_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominacionMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor de la denominación (ej: 1000, 500, 50, 1)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('BILLETE', 'Billete'), ('MONEDA', 'Moneda')], help_text='Si es billete o moneda', max_length=10, verbose_name='Tipo')),
                ('es_activa', models.BooleanField(default=True, help_text='Indica si esta denominación está activa', verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (mayor a menor)', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('moneda', models.ForeignKey(help_text='Moneda a la que pertenece esta denominación', on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='monedas.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Denominación de Moneda',
                'verbose_name_plural': 'Denominaciones de Monedas',
                'db_table': 'monedas_denominacionmoneda',
                'ordering': ['moneda', '-valor', 'tipo'],
                'unique_together': {('moneda', 'valor', 'tipo')},
            },
        ),
    ]
