# Generated by Django 4.2.23 on 2025-09-23 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario_transacciones', models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo permitido para transacciones por día. 0 = sin límite.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Límite Diario de Transacciones')),
                ('limite_mensual_transacciones', models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo permitido para transacciones por mes. 0 = sin límite.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Límite Mensual de Transacciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
