# Generated by Django 4.2.23 on 2025-10-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorDocumentoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_actual', models.IntegerField(default=501, help_text='Número actual del documento (ejemplo: 501 para 0000501)', verbose_name='Número Actual')),
                ('numero_minimo', models.IntegerField(default=501, help_text='Número mínimo permitido del rango', verbose_name='Número Mínimo')),
                ('numero_maximo', models.IntegerField(default=550, help_text='Número máximo permitido del rango', verbose_name='Número Máximo')),
                ('formato_longitud', models.IntegerField(default=7, help_text='Cantidad de dígitos para formatear (ejemplo: 7 para 0000501)', verbose_name='Longitud del Formato')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Contador de Documentos de Factura',
                'verbose_name_plural': 'Contadores de Documentos de Factura',
                'db_table': 'contador_documento_factura',
            },
        ),
    ]
