# Generated by Django 4.2.23 on 2025-09-21 23:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0003_alter_moneda_decimales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del método de cobro (ej: Efectivo, Transferencia bancaria)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del método de cobro')),
                ('comision', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión aplicado (0 a 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('es_activo', models.BooleanField(default=True, help_text='Indica si el método está activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('monedas_permitidas', models.ManyToManyField(help_text='Monedas en las que se puede usar este método de cobro', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Método de Cobro',
                'verbose_name_plural': 'Métodos de Cobro',
                'db_table': 'metodo_cobro_metodocobro',
                'ordering': ['nombre'],
            },
        ),
    ]
