# Generated by Django 4.2.23 on 2025-10-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_pago', '0003_campo_metodopago_campos'),
        ('metodo_cobro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodocobro',
            name='campos',
            field=models.ManyToManyField(blank=True, help_text='Campos específicos requeridos para este método de cobro', to='metodo_pago.campo'),
        ),
    ]
