# Generated by Django 4.2.23 on 2025-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_cobro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodocobro',
            name='requiere_retiro_fisico',
            field=models.BooleanField(default=True, help_text='Indica si este método requiere retiro físico en Tauser (ej: efectivo = True, transferencia = False)'),
        ),
    ]
