# Generated by Django 4.2.23 on 2025-10-17 14:26

from django.db import migrations


def remove_stripe_method(apps, schema_editor):
    """
    Remove the 'Stripe' payment method from the database.
    Stripe functionality is now handled by 'Tarjeta de Crédito' method.
    """
    MetodoCobro = apps.get_model('metodo_cobro', 'MetodoCobro')

    # Delete any MetodoCobro entries with name containing 'stripe' (case-insensitive)
    deleted_count, _ = MetodoCobro.objects.filter(nombre__icontains='stripe').delete()

    if deleted_count > 0:
        print(f"Removed {deleted_count} Stripe payment method(s) from database.")
    else:
        print("No Stripe payment methods found in database.")


def reverse_migration(apps, schema_editor):
    """
    Reverse operation: Re-create Stripe method if needed.
    Note: This won't restore associated data like transactions.
    """
    MetodoCobro = apps.get_model('metodo_cobro', 'MetodoCobro')
    Moneda = apps.get_model('monedas', 'Moneda')

    # Only recreate if it doesn't exist
    if not MetodoCobro.objects.filter(nombre__iexact='stripe').exists():
        stripe_method = MetodoCobro.objects.create(
            nombre='Stripe',
            descripcion='Pago con tarjeta de crédito/débito internacional vía Stripe Checkout',
            comision=2.9,
            es_activo=False  # Create as inactive since we're reversing
        )

        # Associate common currencies
        monedas_codes = ['USD', 'EUR', 'GBP', 'PYG']
        for codigo in monedas_codes:
            try:
                moneda = Moneda.objects.get(codigo=codigo)
                stripe_method.monedas_permitidas.add(moneda)
            except Moneda.DoesNotExist:
                pass

        print("Recreated Stripe payment method (inactive).")


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_cobro', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_stripe_method, reverse_migration),
    ]
