# Generated by Django 4.2.23 on 2025-10-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_cobro', '0002_metodocobro_requiere_retiro_fisico'),
        ('metodo_cobro', '0002_remove_stripe_method'),
    ]

    operations = [
    ]
