# Generated by Django 4.2.23 on 2025-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cedula_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
