# Generated by Django 4.2.23 on 2025-10-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_fecha_actualizacion_usuario_fecha_creacion'),
    ]

    operations = [
    ]
