# Generated by Django 4.2.23 on 2025-10-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_agregar_preferencia_email_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recibir_notificaciones_email',
            field=models.BooleanField(default=False, help_text='Si está activado, recibirás notificaciones de cambios en tasas por correo electrónico', verbose_name='Recibir notificaciones por email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
