# Generated by Django 4.2.23 on 2025-10-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_recibir_notificaciones_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recibir_notificaciones_pago',
            field=models.BooleanField(default=True, help_text='Si está activado, recibirás una notificación cada vez que realices un pago exitoso', verbose_name='Recibir notificaciones de pagos exitosos'),
        ),
    ]
