# Generated by Django 4.2.23 on 2025-10-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_recibir_notificaciones_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='recibir_notificaciones_pago',
            field=models.BooleanField(default=True, help_text='Si está activado, recibirás un correo electrónico cada vez que realices un pago exitoso', verbose_name='Recibir notificaciones de pagos exitosos por email'),
        ),
    ]
