# Generated by Django 4.2.23 on 2025-09-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadotransaccion',
            name='codigo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], max_length=15, unique=True, verbose_name='Código del estado'),
        ),
    ]
