# Generated by Django 4.2.23 on 2025-09-26 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_estadotransaccion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total de comisión en la moneda origen', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Comisión'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total de descuento aplicado', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Descuento'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Porcentaje de comisión aplicado', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Comisión (%)'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Porcentaje de descuento aplicado por tipo de cliente', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Descuento (%)'),
        ),
    ]
