# Generated by Django 4.2.23 on 2025-10-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0002_stock'),
        ('clientes', '0005_cliente_monto_limite_transaccion'),
        ('transacciones', '0003_aumentar_precision_decimales'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tauser',
            field=models.ForeignKey(blank=True, help_text='Punto de atención donde se realiza la transacción (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='tauser.tauser', verbose_name='Tauser'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente que realiza la transacción (opcional para clientes casuales)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tauser', '-fecha_creacion'], name='transaccion_tauser__fed26e_idx'),
        ),
    ]
