# Generated by Django 4.2.23 on 2025-10-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_monto_limite_transaccion'),
        ('transacciones', '0003_aumentar_precision_decimales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente que realiza la transacción (opcional para clientes casuales)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='PagoPasarela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago_externo', models.CharField(help_text='ID del pago en la pasarela externa', max_length=100, unique=True, verbose_name='ID Pago Externo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('metodo_pasarela', models.CharField(help_text='Método de pago según la pasarela (tarjeta, efectivo, transferencia)', max_length=50, verbose_name='Método en Pasarela')),
                ('moneda', models.CharField(max_length=10, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('exito', 'Éxito'), ('fallo', 'Fallo'), ('pendiente', 'Pendiente')], max_length=20, verbose_name='Estado del Pago')),
                ('datos_pago', models.JSONField(blank=True, default=dict, help_text='Información adicional del pago (datos de tarjeta enmascarados, etc.)', verbose_name='Datos del Pago')),
                ('respuesta_pasarela', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de la pasarela de pagos', verbose_name='Respuesta de Pasarela')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, help_text='Fecha en que se procesó el pago en la pasarela', null=True, verbose_name='Fecha de Procesamiento')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el pago falló', verbose_name='Mensaje de Error')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_pasarela', to='transacciones.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Pago de Pasarela',
                'verbose_name_plural': 'Pagos de Pasarela',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['id_pago_externo'], name='transaccion_id_pago_b4d1f7_idx'), models.Index(fields=['transaccion', '-fecha_creacion'], name='transaccion_transac_94f82d_idx'), models.Index(fields=['estado', '-fecha_creacion'], name='transaccion_estado_eb94bb_idx')],
            },
        ),
    ]
