# Generated by Django 4.2.23 on 2025-10-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_alter_transaccion_cliente_pagopasarela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoPasarela',
        ),
    ]
