# Generated by Django 4.2.23 on 2025-10-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_delete_pagopasarela'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_operate', 'Puede realizar operaciones de compra y venta')], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
