# Generated by Django 4.2.23 on 2025-10-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0006_alter_transaccion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='de_id',
            field=models.BigIntegerField(blank=True, help_text='ID del DE generado en SQL-Proxy para facturación', null=True, verbose_name='ID del Documento Electrónico'),
        ),
    ]
