# Generated by Django 4.2.23 on 2025-10-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_transaccion_tauser_alter_transaccion_cliente_and_more'),
        ('transacciones', '0006_alter_transaccion_options'),
    ]

    operations = [
    ]
