# Generated by Django 4.2.23 on 2025-10-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0008_agregar_estados_entregada_retirado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='datos_metodo_pago',
            field=models.JSONField(blank=True, default=dict, help_text='Información adicional requerida por el método de pago seleccionado (número de cuenta, billetera, etc.)', verbose_name='Datos del Método de Pago'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='registro_deposito',
            field=models.JSONField(blank=True, default=dict, help_text='Información del depósito realizado al cliente mediante el simulador', verbose_name='Registro del Depósito'),
        ),
    ]
