# Generated by Django 4.2.23 on 2025-10-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0007_add_de_id_field'),
        ('transacciones', '0008_agregar_estados_entregada_retirado'),
    ]

    operations = [
    ]
