# Generated by Django 4.2.23 on 2025-10-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0009_merge_20251031_0328'),
        ('transacciones', '0009_transaccion_datos_metodo_pago_and_more'),
    ]

    operations = [
    ]
