# Generated by Django 4.2.23 on 2025-11-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0010_merge_20251031_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_operate', 'Puede realizar operaciones de compra y venta'), ('view_reporte_transacciones', 'Puede ver reporte de transacciones'), ('view_reporte_ganancias', 'Puede ver reporte de ganancias')], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
