# Generated by Django 4.2.23 on 2025-11-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0010_merge_20251031_1246'),
        ('transacciones', '0011_alter_transaccion_options'),
    ]

    operations = [
    ]
