# Generated by Django 4.2.23 on 2025-11-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0012_merge_20251125_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tasa_cambio_base',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de cambio sin descuentos (precio_base +/- comisión de cambio). Usado para calcular ganancia real.', max_digits=12, null=True, verbose_name='Tasa de Cambio Base'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=4, help_text='Tasa de cambio aplicada en la transacción (con descuentos aplicados)', max_digits=12, verbose_name='Tasa de Cambio'),
        ),
    ]
