# Generated by Django 4.2.23 on 2025-11-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0013_add_tasa_cambio_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio base de la tasa de cambio al momento de la transacción (sin comisiones de cambio)', max_digits=12, null=True, verbose_name='Precio Base'),
        ),
    ]
