# Generated by Django 4.2.23 on 2025-09-15 14:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del método de pago (ej: Efectivo, Tarjeta de Crédito)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del método de pago')),
                ('comision', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión aplicado (0 a 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('es_activo', models.BooleanField(default=True, help_text='Indica si el método está activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodo_pago_metodopago',
                'ordering': ['nombre'],
            },
        ),
    ]
