# Generated by Django 4.2.23 on 2025-09-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0004_moneda_monto_limite_transaccion'),
        ('metodo_pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='monedas_permitidas',
            field=models.ManyToManyField(help_text='Monedas en las que se puede usar este método de pago', to='monedas.moneda'),
        ),
    ]
