# Generated by Django 4.2.23 on 2025-10-16 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_pago', '0002_metodopago_monedas_permitidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del campo (ej: numero_telefono, documento)', max_length=100, unique=True)),
                ('etiqueta', models.CharField(help_text='Etiqueta a mostrar en el formulario', max_length=100)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('email', 'Email'), ('phone', 'Teléfono'), ('select', 'Selección'), ('textarea', 'Área de texto')], default='text', help_text='Tipo de campo HTML', max_length=20)),
                ('es_obligatorio', models.BooleanField(default=True, help_text='Indica si el campo es obligatorio')),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='Longitud máxima del campo', null=True)),
                ('regex_validacion', models.CharField(blank=True, help_text='Expresión regular para validación', max_length=500)),
                ('placeholder', models.CharField(blank=True, help_text='Texto de ayuda para el campo', max_length=200)),
                ('opciones', models.TextField(blank=True, help_text='Opciones para campos de selección (una por línea)')),
                ('es_activo', models.BooleanField(default=True, help_text='Indica si el campo está activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'db_table': 'metodo_pago_campo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='metodopago',
            name='campos',
            field=models.ManyToManyField(blank=True, help_text='Campos específicos requeridos para este método de pago', to='metodo_pago.campo'),
        ),
    ]
