# Generated by Django 4.2.23 on 2025-10-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_pago', '0003_campo_metodopago_campos'),
        ('metodo_pago', '0003_metodopago_requiere_retiro_fisico'),
    ]

    operations = [
    ]
