# Generated by Django 4.2.23 on 2025-08-21 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.permiso'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.rol'),
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', through='roles.RolPermiso', to='roles.permiso'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='roles.modulo'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol')},
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='permiso',
            unique_together={('codigo', 'modulo')},
        ),
    ]
