# Generated by Django 4.2.23 on 2025-08-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocliente',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (%)'),
        ),
    ]
