# Generated by Django 4.2.23 on 2025-08-22 16:17

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cedula_usuario_fecha_nacimiento'),
        ('clientes', '0002_tipocliente_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(default='', help_text='Nombre comercial o razón social del cliente', max_length=200, verbose_name='Nombre Comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(default='', help_text='Número de RUC del cliente', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe contener solo números y tener entre 5 y 20 dígitos.', regex='^\\d{5,20}$')], verbose_name='RUC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(help_text='Dirección completa del cliente', verbose_name='Dirección', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(help_text='Correo electrónico de contacto del cliente', max_length=254, verbose_name='Correo Electrónico', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_telefono',
            field=models.CharField(help_text='Número de teléfono de contacto', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener solo números, espacios, guiones, paréntesis y el símbolo +.', regex='^[\\d\\s\\-\\+\\(\\)]+$')], verbose_name='Número de Teléfono', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(help_text='Tipo de cliente que determina el descuento aplicable', on_delete=django.db.models.deletion.PROTECT, to='clientes.tipocliente', verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarios_asociados',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que pueden operar en nombre de este cliente', to='usuarios.usuario', verbose_name='Usuarios Asociados'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el cliente está activo en el sistema', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
