# Generated by Django 4.2.23 on 2025-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20250822_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_comercial'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ruc'], name='clientes_cl_ruc_79b45b_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre_comercial'], name='clientes_cl_nombre__3c4a08_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tipo_cliente'], name='clientes_cl_tipo_cl_031765_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='clientes_cl_activo_b76065_idx'),
        ),
    ]
