# Generated by Django 4.2.23 on 2025-09-23 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='monto_limite_transaccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo permitido para una sola transacción. Dejar vacío para sin límite.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto límite por transacción'),
        ),
    ]
