# Generated by Django 4.2.23 on 2025-10-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_monto_limite_transaccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_comercial'], 'permissions': [('can_view_all_clients', 'Puede ver todos los clientes')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
