# Generated by Django 4.2.23 on 2025-10-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_comercial'], 'permissions': [('can_view_all_clients', 'Puede ver todos los clientes'), ('can_view_sensitive_columns', 'Puede ver columnas sensibles (usuarios asociados, estado, fecha creación)')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
