# Generated by Django 4.2.23 on 2025-10-31 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dv',
            field=models.CharField(blank=True, help_text='Dígito verificador del RUC', max_length=1, null=True, validators=[django.core.validators.RegexValidator(message='El DV debe ser un solo dígito numérico.', regex='^\\d$')], verbose_name='DV'),
        ),
    ]
