# Generated by Django 4.2.23 on 2025-09-04 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código de Verificación')),
                ('tipo', models.CharField(choices=[('login', 'Inicio de Sesión'), ('registro', 'Registro de Usuario'), ('reset_password', 'Reseteo de Contraseña')], max_length=20, verbose_name='Tipo de Verificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Código de Verificación',
                'verbose_name_plural': 'Códigos de Verificación',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo', 'tipo'], name='custom_auth_codigo_7501f9_idx'), models.Index(fields=['usuario', 'tipo'], name='custom_auth_usuario_2388cb_idx'), models.Index(fields=['fecha_expiracion'], name='custom_auth_fecha_e_d2a93c_idx')],
            },
        ),
    ]
