# Generated by Django 4.2.23 on 2025-08-31 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0003_alter_moneda_decimales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_compra', models.DecimalField(decimal_places=4, help_text='Tasa de compra de la moneda (precio al que se compra)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('tasa_venta', models.DecimalField(decimal_places=4, help_text='Tasa de venta de la moneda (precio al que se vende)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('fecha_vigencia', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora desde la cual la cotización está vigente')),
                ('es_activa', models.BooleanField(default=True, help_text='Indica si la cotización está activa para operaciones')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('moneda', models.OneToOneField(help_text='Moneda para la cual se establece la cotización', on_delete=django.db.models.deletion.CASCADE, related_name='tasa_cambio', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'db_table': 'tasa_cambio_tasacambio',
                'ordering': ['-fecha_vigencia', 'moneda__nombre'],
            },
        ),
    ]
