# Generated by Django 4.2.23 on 2025-08-31 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasa_cambio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='tasa_compra',
            field=models.DecimalField(decimal_places=8, help_text='Tasa de compra de la moneda (precio al que se compra)', max_digits=15, validators=[django.core.validators.MinValueValidator(1e-08)]),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='tasa_venta',
            field=models.DecimalField(decimal_places=8, help_text='Tasa de venta de la moneda (precio al que se vende)', max_digits=15, validators=[django.core.validators.MinValueValidator(1e-08)]),
        ),
    ]
