# Generated by Django 4.2.23 on 2025-08-31 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0003_alter_moneda_decimales'),
        ('tasa_cambio', '0002_alter_tasacambio_tasa_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='moneda',
            field=models.ForeignKey(help_text='Moneda para la cual se establece la cotización', on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio', to='monedas.moneda'),
        ),
        migrations.AddConstraint(
            model_name='tasacambio',
            constraint=models.UniqueConstraint(condition=models.Q(('es_activa', True)), fields=('moneda', 'es_activa'), name='unique_active_tasa_cambio_per_moneda'),
        ),
    ]
