# Generated by Django 4.2.23 on 2025-08-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasa_cambio', '0003_alter_tasacambio_moneda_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tasacambio',
            name='unique_active_tasa_cambio_per_moneda',
        ),
    ]
