# Generated by Django 4.2.23 on 2025-09-18 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasa_cambio', '0004_remove_tasacambio_unique_active_tasa_cambio_per_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasacambio',
            name='tasa_compra',
        ),
        migrations.RemoveField(
            model_name='tasacambio',
            name='tasa_venta',
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='comision_compra',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Comisión que se resta al precio base para obtener el precio de compra', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='comision_venta',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Comisión que se suma al precio base para obtener el precio de venta', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='precio_base',
            field=models.DecimalField(decimal_places=8, default=1, help_text='Precio base de la moneda (cotización de referencia)', max_digits=15, validators=[django.core.validators.MinValueValidator(1e-08)]),
        ),
    ]
