# Generated by Django 4.2.23 on 2025-09-19 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasa_cambio', '0005_remove_tasacambio_tasa_compra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasacambio',
            options={'ordering': ['-fecha_vigencia', 'moneda__nombre'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='comision_compra',
            field=models.PositiveIntegerField(default=0, help_text='Comisión en guaraníes que se resta al precio base para obtener el precio de compra', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='comision_venta',
            field=models.PositiveIntegerField(default=0, help_text='Comisión en guaraníes que se suma al precio base para obtener el precio de venta', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='precio_base',
            field=models.PositiveIntegerField(default=1, help_text='Precio base de la moneda en guaraníes (valor entero)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
