# Generated by Django 4.2.23 on 2025-09-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasa_cambio', '0006_alter_tasacambio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasacambio',
            options={'ordering': ['-fecha_creacion', 'moneda__nombre'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.RemoveField(
            model_name='tasacambio',
            name='fecha_vigencia',
        ),
    ]
