# Generated by Django 4.2.23 on 2025-10-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasa_cambio', '0007_alter_tasacambio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasacambio',
            options={'ordering': ['-fecha_creacion', 'moneda__nombre'], 'permissions': [('can_view_sensitive_columns', 'Puede ver columnas sensibles (precio base, comisiones, spread, fecha, estado)')], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
